### ISSUE TITLE
Falied to run elm-make

### ISSUE THREAD

**Issue by ampc** [mybuddymichael/linter-elm-make#2]
```
Failed to run /usr/local/bin/elm-make
spawn /usr/local/bin/elm-make ENOENT
```

![screen shot 2015-08-29 at 22 35 14](https://cloud.githubusercontent.com/assets/284907/9564405/4a5851e2-4e9e-11e5-9bee-fcb5ea84ad01.png)

Tested another elm linter in SublimeText and it's working so I doubt the root of problem is elm-make binary. Thanks.

**Comment by skovsboll** [comment]
Here's what worked for me:
1. Follow the installation steps in the [README](https://github.com/mybuddymichael/linter-elm-make/blob/master/README.md)
2. Open atom settings
3. Click _Open the config folder_
4. Open the `config.cson` file in the root
5. Add this snippet inside the `"*"` node:

```
  "linter-elm-make":
    elmMakeExecutablePath: "/usr/local/bin/elm-make"
```

> Remember to replace the path with your own path that you got with `which elm-make`

Finally, disable and enable linter-elm-make

**Comment by wstrinz** [comment]
I'm having this issue as well. The snippet @skovsboll posted was already in my `config.cson` (I think because I'd set the elm path in the packages settings)

edit: hmm, I tried opening atom in dev mode to see if I could get more error info, and it works now! (in both modes). Might have just needed to close and restart atom or reload the project, not sure.

**Comment by tulis** [comment]
Not sure if this is the right place to post my problem since it's slightly different. 
The linter does not seems doing anything and I even did not get any error message like "Failed to run...". I have followed all the steps mentioned in [README](https://github.com/mybuddymichael/linter-elm-make/blob/master/README.md). Here is my config.cson:

```
  "language-elm": {}
  linter:
    showErrorTabLine: true
  "linter-elm-make":
    elmMakeExecutablePath: "C:\\Program Files (x86)\\Elm Platform\\0.15.1\\bin\\elm-make.exe"
".elm.source":
  editor:
    autoIndentOnPaste: true

```

Is there anything I missed?

**Comment by ThomasWeiser** [comment]
I also had this issues...

First there was the mentioned `Failed to run ... ENOENT` error.
Then after some restarting there message is gone, but also the attempt to spawn elm-make.
After more restarting it now works.

Can't help more, I'm totally new to Atom.

**Comment by tulis** [comment]
Hi, @ThomasWeiser 

When you said restart, was it the Atom editor or the OS? Tried many times restarting the editor, but no avail.

I'm also new to Atom, only install it just for elm.

**Comment by ThomasWeiser** [comment]
I restarted Atom, not the OS (which is Linux here).
I also tried to go into dev mode, but didn't know how exactly, so may be I did.
So after some fiddling, it suddenly worked.

**Comment by wstrinz** [comment]
Confirmed (for me at least) that this plugin only works in dev mode. For any atom newbies like myself who run across this, dev mode can be accessed using `View -> Developer -> Open In Dev Mode...`

I'll have a look and see if I can find what makes that necessary, and submit a PR if I discover anything.

**Comment by thSoft** [comment]
@wstrinz could you please try the latest version of Atom & linter-elm-make not in dev-mode? It should work now.

**Comment by wstrinz** [comment]
@thSoft working great on Windows with the latest version of everything for me. Thanks!

**Comment by thSoft** [comment]
Cool, thanks for trying!

**Comment by lucymonie** [comment]
I'm on Linux and I had this problem. I read these comments and restarted Atom and bingo - the error went away. Thanks!

**Comment by BigTom** [comment]
I am on MacOS Sierra and have run into this problem.  Restarting OS and App did not resolve it but running in Dev mode has.

**Comment by 3nigm4** [comment]
I am on Windows 10 this Problem still exists, dev mode works...
